import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import LoginForm from "../components/LoginForm";
import { Card, Typography } from "@mui/material";

const Home: NextPage = () => {
  // const todo = useSelector((state: RootState) => state.todo);
  // console.log(todo);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Card raised={true} sx={{
          padding: '1em'
        }}>
          <Typography align="center">Enter your username</Typography>
          <LoginForm />
        </Card>
      </main>

      {/* <footer className={styles.footer}>
        
      </footer> */}
    </div>
  );
};

export default Home;
